### ISSUE TITLE
[data grid] GridToolbarQuickFilter doesn't keep pre-selected rows

### ISSUE THREAD

**Issue by max-tian-123** [mui/mui-x#15182]
### Search keywords

DataGrid GridToolbarQuickFilter pre-selected

### Latest version

- [X] I have tested the latest version

### Affected products

Data Grid

### Steps to reproduce

Link to live example: [(required)](https://mui.com/x/react-data-grid/row-selection/#system-DisableClickSelectionGrid.js)

Steps:
1. Find an official example from mui web-site which enabled quick filter toolbar. For example, [Disable row selection on click](https://mui.com/x/react-data-grid/row-selection/#system-DisableClickSelectionGrid.js). And enable checkbox selection.
![Screenshot 2024-10-30 at 13 40 05](https://github.com/user-attachments/assets/7aefaecc-ae76-4c79-a58f-672455426cc3)
2. Select two rows.
![Screenshot 2024-10-30 at 13 40 22](https://github.com/user-attachments/assets/d8cc7d1f-1d2d-4561-bf9d-2ef8740e359c)
3. Search one of them.
![Screenshot 2024-10-30 at 13 40 39](https://github.com/user-attachments/assets/cfb65f90-81e9-4b5c-a71e-596982112411)
Please check the selected rows and number.
4. Clean the quick filter value.
![Screenshot 2024-10-30 at 13 40 52](https://github.com/user-attachments/assets/860bdf4d-3c76-45db-8ec8-a57bf967369a)
There is only one row has been selected.

I compared with version 6.0, this action has been changed. Please tell me it is a bug or not. I am very happy to know the root cause. Thanks.

### Current behavior

The pre-selected rows will be de-selected except the one matched quick filter value after the filter take effect in DataGrid component.

### Expected behavior

The behavior of quick filter in component DataGrid should keep the same with version 6.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 15.0.1
  Binaries:
    Node: 18.20.3 - /opt/homebrew/opt/node@18/bin/node
    npm: 10.7.0 - /opt/homebrew/opt/node@18/bin/npm
    pnpm: 9.5.0 - ~/.nvm/versions/node/v18.20.3/bin/pnpm
  Browsers:
    Chrome: 129.0.6668.101 (Official Build) (arm64)
    Edge: Not Found
    Safari: 18.0.1
```
</details>

**Comment by max-tian-123** [comment]
Thank you @arminmeh , I just verified. It worked.

**Comment by max-tian-123** [comment]
Hi @arminmeh ,
I think this issue is not about `keepNonExistentRowsSelected` feature. By default, this feature is disabled. But, the action is performed on v7 and v6 with `keepNonExistentRowsSelected=false`. I think this behavior has been changed when I migrate from v6 to v7.

**Comment by arminmeh** [comment]
Hi @max-tian-123 

It looks like the root cause is the way the selection is sanitized with `keepNonExistentRowsSelected=false` (`false` is default for both [v6](https://github.com/mui/mui-x/blob/v6.x/packages/grid/x-data-grid/src/DataGrid/useDataGridProps.ts#L80) and [v7](https://github.com/mui/mui-x/blob/v7.x/packages/x-data-grid/src/constants/dataGridPropsDefaultValues.ts#L42))

In v6, check was done against [`rowsLookup`](https://github.com/mui/mui-x/blob/v6.x/packages/grid/x-data-grid/src/hooks/features/rowSelection/useGridRowSelection.ts#L328), while in the latest v7 this is done against [`filteredRowsLookup`](https://github.com/mui/mui-x/blob/v7.x/packages/x-data-grid/src/hooks/features/rowSelection/useGridRowSelection.ts#L452).

Change was made in https://github.com/mui/mui-x/pull/14677 to address other issue, but you can see the mention of the issue that actually requires removing filtered out rows
https://github.com/mui/mui-x/issues/11726

Another related issue https://github.com/mui/mui-x/pull/11751

From my perspective, it looks like the default v6 behavior is false, since `keepNonExistentRowsSelected=false` means do not keep selection on filtered out rows.

I hope that his clarifies it a bit

@MBilalShafi do you have any additional comments, since you were involved in these changes?

**Comment by MBilalShafi** [comment]
Yes, this behavior was corrected in v7. Unfiltered rows won't be selected after filtering unless `keepNonExistentRowsSelected` is passed. Based on the need, we might consider porting it to v6 too.

**Comment by max-tian-123** [comment]
Hi @arminmeh @MBilalShafi ,
I understand what mentioned above. In my view, filtering and checking are total different behaviors. Please consider a scenario, there are some data which fetched from database and represented in page with checked boxes in DataGrid, then user wants to use quick filter to filter out some special data, here the behavior is changed, the user doesn't want to uncheck those data in DataGrid, just wants to filter out a portion of them. But now, another portion of data have been unchecked. Think about that, the unchecked data list could be hundreds. That behavior makes user confused, they just want to filter out, they don't want to uncheck.

**Comment by arminmeh** [comment]
That is a valid request.

What we have stated is that we believe that the behavior on v6 is incorrect.
To achieve what you are describing `keepNonExistentRowsSelected` should be set to `true`.

My understanding is that you are asking why it was working with the value `false` before and not anymore.
Is this correct or you are saying that even with the flag set to `true` the behavior is still not correct?

**Comment by max-tian-123** [comment]
I tried with `keepNonExistentRowsSelected=true`, but the total row number is incorrect with selected rows in v7.

**Comment by arminmeh** [comment]
Can you please share reproduction code?

I have just tried it out and I don't see any issue
Here is [my sandbox](https://codesandbox.io/p/sandbox/row-selection-and-filtering-example-5hgsh8?file=%2Fsrc%2FDemo.tsx)

<img width="701" alt="selection" src="https://github.com/user-attachments/assets/dfb64a60-0d80-4ac5-bf1d-773dca9857b8">

<img width="701" alt="filtering" src="https://github.com/user-attachments/assets/15a744f3-da3d-4583-8862-828b2a63560a">

**Comment by max-tian-123** [comment]
I think maybe I can change the process logic to avoid such situation. BTW, if the behavior is considered as correct, just no fighting, let me close the issue. Thank you for your comments.

**Comment by arminmeh** [comment]
@max-tian-123 
in case you get to the point where you cannot work around the issue that you have, feel free to re-open this issue and we can try to help you further
