### ISSUE TITLE
CheckboxSelection 'Select All' is not working on DataGridPremium using own GridRowSelectionModel

### ISSUE THREAD

**Issue by smolerovic** [mui/mui-x#18566]
### Steps to reproduce

Steps: Copy the code, click on 'Select All' and check both console.logs
- MUI version: "@mui/x-data-grid-premium": "^8.5.3",

```
import { Box } from '@mui/material';
import type { GridColDef } from '@mui/x-data-grid';
import { DataGrid } from '@mui/x-data-grid';
import {
  DataGridPremium,
  GridRowSelectionModel,
} from '@mui/x-data-grid-premium';
import { useState } from 'react';

const columns: GridColDef[] = [
  { field: 'id', headerName: 'ID', width: 90 },
  { field: 'firstName', headerName: 'First name', width: 150 },
  { field: 'lastName', headerName: 'Last name', width: 150 },
  { field: 'age', headerName: 'Age', type: 'number', width: 110 },
];

const rows = [
  { id: 1, lastName: 'Snow', firstName: 'Jon', age: 35 },
  { id: 2, lastName: 'Lannister', firstName: 'Cersei', age: 42 },
  { id: 3, lastName: 'Lannister', firstName: 'Jaime', age: 45 },
];

const TestExample = () => {
  const [
    rowSelectionModelDataGridPremium,
    setRowSelectionModelDataGridPremium,
  ] = useState<GridRowSelectionModel>({ type: 'include', ids: new Set() });

  const [rowSelectionModelTwoDataGrid, setRowSelectionModelTwoDataGrid] =
    useState<GridRowSelectionModel>({ type: 'include', ids: new Set() });

  console.log(
    '🚀 ~ DataGridTest ~ rowSelectionModelDataGridPremium:',
    rowSelectionModelDataGridPremium,
  ); // this is not working when 'Select All' is clicked - ids: Set(0)

  console.log(
    '🚀 ~ DataGridTest ~ rowSelectionModelTwoDataGrid:',
    rowSelectionModelTwoDataGrid,
  ); // this is working when 'Select All' is clicked - ids: Set(3)

  return (
    <Box>
      <DataGridPremium
        rows={rows}
        columns={columns}
        checkboxSelection
        onRowSelectionModelChange={setRowSelectionModelDataGridPremium}
        rowSelectionModel={rowSelectionModelDataGridPremium}
      />
      <DataGrid
        rows={rows}
        columns={columns}
        checkboxSelection
        onRowSelectionModelChange={setRowSelectionModelTwoDataGrid}
        rowSelectionModel={rowSelectionModelTwoDataGrid}
      />
    </Box>
  );
};

export default TestExample;

```

### Current behavior

When 'Select All' is checked, using <DataGridPremium /> there are no ids selected in rowSelectionModel
This is working correctly if I switched on <DataGrid />

### Expected behavior

It should work the same for <DataGridPremium />

**Search keywords**: checkboxSelection, DataGridPremium, onRowSelectionModelChange, rowSelectionModel

**Comment by GMchris** [comment]
To add some context, I went a bit back and found that the latest version where this bug doesn't reproduce is `8.3.1`

**Comment by smolerovic** [comment]
Does anyone have any updates on this? Please let me know if you need more details.

**Comment by arminmeh** [comment]
Hey all,

reason for this is that from v8, grid uses either `include` or `exclude` selection model, based on the current grid state and the user action
This has been implemented in https://github.com/mui/mui-x/pull/15651
Migration guide section https://mui.com/x/migration/migration-data-grid-v7/#selection

`DataGrid` and `DataGridPremium` behave differently, because the community version of the grid does not support [multiple row selection](https://mui.com/x/react-data-grid/row-selection/#multiple-row-selection) which is one of the conditions to switch to the `exclude` model.

>To add some context, I went a bit back and found that the latest version where this bug doesn't reproduce is 8.3.1

@GMchris this might be because of the `exclude` model condition has been updated in version 8.4.0 by https://github.com/mui/mui-x/pull/17899

Let me know if you need more info regarding this topic

**Comment by arminmeh** [comment]
CC @cherniavskii

**Comment by smolerovic** [comment]
@arminmeh @cherniavskii please let me know if you need any clarification or additional details about the issue. I'm happy to help and share any information you need. Thanks!

**Comment by arminmeh** [comment]
@smolerovic 

In the comment above I have written
>reason for this is that from v8, grid uses either include or exclude selection model, based on the current grid state and the user action
This has been implemented in https://github.com/mui/mui-x/pull/15651
Migration guide section [mui.com/x/migration/migration-data-grid-v7#selection](https://mui.com/x/migration/migration-data-grid-v7/#selection)
>
>DataGrid and DataGridPremium behave differently, because the community version of the grid does not support [multiple row selection](https://mui.com/x/react-data-grid/row-selection/#multiple-row-selection) which is one of the conditions to switch to the exclude model.

Does this clarify the reason behind having an empty selection array. Or your issue is that you don't get what I have described?

**Comment by smolerovic** [comment]
https://github.com/user-attachments/assets/1fbe4ab7-1c4a-498e-8830-94ab157f2145

Hi @arminmeh , thanks for the quick reply!

Not really. I understand there’s a difference between the community and premium versions, etc. But this is a really basic example of selecting “all.”
Please take a look at the recording I provided. It uses the same code I pasted above.

If you believe this is the expected behavior, could you please let me know the correct approach to get all IDs when “Select All” is checked?

**Comment by michelengelen** [comment]
The way to go about this has already been raised several times now and @MBilalShafi has provided a great explanation and showcase here: https://github.com/mui/mui-x/issues/17485#issuecomment-2839905603

**Comment by cherniavskii** [comment]
The behavior is now consistent between DataGrid and DataGridPremium – both will use exclusion model (`type: 'exclude', ids: new Set()`) when selecting all rows, see updated demo: https://stackblitz.com/edit/8uulhr4g-swp7fezu?file=src%2FDemo.tsx

This was fixed by https://github.com/mui/mui-x/pull/18844 and released in https://github.com/mui/mui-x/releases/tag/v8.9.1

**Comment by paul-vd** [comment]
Hello @cherniavskii , I'm on version 8.10.1 and experiencing this issue after following the docs: https://mui.com/x/react-data-grid/row-selection/#controlled-row-selection

I'm using DataGridPremium, also your demo seems to still have the issue.

**Comment by arminmeh** [comment]
@paul-vd 
What is the issue you are referring to?
Inconsistency between the DataGrid and DataGridPremium?

In the linked demo, selecting all rows generates the following selection model
`{type: 'exclude', ids: Set(0)}`
which is expected.

Internally, we discussed having an option to opt out of the`exclude` model, but I can't find the issue
@MBilalShafi do you have a link to it?

**Comment by MBilalShafi** [comment]
> [@paul-vd](https://github.com/paul-vd) What is the issue you are referring to? Inconsistency between the DataGrid and DataGridPremium?
> 
> In the linked demo, selecting all rows generates the following selection model `{type: 'exclude', ids: Set(0)}` which is expected.
> 
> Internally, we discussed having an option to opt out of the`exclude` model, but I can't find the issue [@MBilalShafi](https://github.com/MBilalShafi) do you have a link to it?

There wasn't one. I just created it: https://github.com/mui/mui-x/issues/19418

**Comment by paul-vd** [comment]
So if I understand correctly, with the current API I need to explicitly list all "selections" when I use the select all checkbox, instead of the API working as anyone would expect it to work →  updating the selection model with all selected rows.

eg:
```ts
  const selectedRows = useMemo(() => {
    if (
      rowSelectionModel.type === "exclude" &&
      rowSelectionModel.ids.size === 0
    ) {
      return data || [];
    }

    return data.filter((row) => rowSelectionModel.ids.has(row.id));
  }, [data, rowSelectionModel]);
```

instead of just having:
```ts
  const selectedRows = useMemo(() => {
    return data.filter((row) => rowSelectionModel.ids.has(row.id));
  }, [data, rowSelectionModel]);
```

it's quite confusing having this mix and match of patterns, is this done for performance reasons or something?

**Comment by MBilalShafi** [comment]
> is this done for performance reasons or something

Exactly, here's some more context: https://github.com/mui/mui-x/issues/17485#issuecomment-2820888829 and https://github.com/mui/mui-x/issues/17485#issuecomment-2839905603

And in case performance is not your concern, you can opt out of this behavior starting next release. (Related PR: https://github.com/mui/mui-x/pull/19423)
