### ISSUE TITLE
[tree view] Switch between 'defaultExpandedItems' and 'expandedItems' features

### ISSUE THREAD

**Issue by AlexM392** [mui/mui-x#18723]
### The problem in depth

I'm trying to implement a search mechanism on a Tree View. I want sections containing the nodes I'm looking for to be expanded when an array of nodes to expand is passed to the tree.
Before I started working with search, I used defaultExpandedItems to keep the root node of my tree always expanded. Now, I assumed that I should use conditions in this property - defaultExpandedItems={nodesToExpand.length !== 0 nodesToExpand : [rootId]}
However, I got the following error in the console: "MUI X: A component is changing the default expandedItems state of an uncontrolled Tree View after being initialized. To suppress this warning opt to use a controlled Tree View.". I understand that I need to use the expandedItems property, but I will need to control the array of expanded nodes myself. 
Is there a way to switch between these two properties, defaultExpandedItems and expandedItems? 
If an array of nodes is passed to the tree for opening, should I use expandedItems, and if this array is empty, then use defaultExpandedItems? 
Or should I somehow pass an array of nodes to open in defaultExpandedItems and leave the opening of nodes uncontrolled?

Please check the [DEMO](https://stackblitz.com/edit/sg8yo3xl?file=src%2FDemo.jsx)

### Your environment

<details>
  <summary>npx @mui/envinfo</summary>

```
System:
    OS: Windows 11 10.0.26100
  Binaries:
    Node: 22.15.0 
    npm: 10.9.2 
    pnpm: Not Found
  Browsers:
    Chrome: Not Found
    Edge: Chromium (135.0.3179.54)
  npmPackages:
    @emotion/react: 11.9.0 => 11.9.0
    @emotion/styled: 11.8.1 => 11.8.1
    @mui/core-downloads-tracker:  5.17.1
    @mui/icons-material: 5.6.2 => 5.6.2
    @mui/material: 5.17.1 => 5.17.1
    @mui/private-theming:  6.4.9
    @mui/styled-engine:  6.4.11
    @mui/styled-engine-sc: 5.7.0 => 5.7.0
    @mui/system: 6.3.1 => 6.3.1
    @mui/types:  7.2.24
    @mui/utils:  5.17.1
    @mui/x-date-pickers:  8.0.0
    @mui/x-date-pickers-pro: 8.0.0 => 8.0.0
    @mui/x-internals:  8.0.0
    @mui/x-license: 8.0.0 => 8.0.0
    @mui/x-telemetry:  8.0.0
    @mui/x-tree-view: 7.29.0 => 7.29.0
    @mui/x-tree-view-pro: 7.29.0 => 7.29.0
    @types/react: 17.0.2 => 17.0.2
    react: 17.0.2 => 17.0.2
    react-dom: 17.0.2 => 17.0.2
    styled-components: 5.3.3 => 5.3.3
    typescript: 5.1.6 => 5.1.6
```
</details>

I'm using Chrome version 137.0.7151.120 (Official Build) (64-bit)

**Search keywords**: Uncontrolled item's expantion

**Order ID**: 101599

**Comment by LukasTy** [comment]
Hello @AlexM392.
You can read more about the controlled vs uncontrolled concept [here](https://mui.com/material-ui/guides/api/#controlled-components).
In general, you should use one or the other approach.
Our components do not support dynamically switching between the approaches, without remounting the component.

Are you having issues settling only on controlled usage? 🤔 

By the way, your demo is probably private.

___

### A note regarding your output of `@mui/envinfo`
Have you tried aligning on package versions? At least on the X components side?
Technically, it should work, but to avoid any strange issues, I'd recommend updating your packages to the latest major version. 👍

**Comment by AlexM392** [comment]
Hello @LukasTy.
Thank you for such a quick response.
I'll read about controlled vs uncontrolled concept.
To say the truth, I have a problem because I want to use uncontrolled version with the date received outside.
Sorry for the private demo. I've made it public.
No, I've never tried aligning on package versions. Right now everything works properly.

**Comment by LukasTy** [comment]
> To say the truth, I have a problem because I want to use uncontrolled version with the date received outside.
> Sorry for the private demo. I've made it public.

If you are trying to do something similar to what is shown in the demo, then you need to opt for controlling the `expandedItems`, because you clearly want to control them. 🤔 
The `defaultExpandedItems` is only there to initialize the expanded items in case you don't need programatic control over them.
I assume, that in 99% of Tree View cases, a controlled version is needed.
The uncontrolled concept works and makes more sense for regular input components, where their data could be parsed by native means (i.e. `FormData`).

> No, I've never tried aligning on package versions. Right now everything works properly.

I'm glad to hear you are not having issues with it, but to me, the resolved package versions look slightly alarming (Material v5, System v6, Pickers v8, TreeView v7).
Friendly suggestion to plan some time to first align `@mui/x-tree view` and `@mui/x-date-pickers` major versions.
And then, consider a bump to Material v7 (or first v6) somewhere down the line. 👍

**Comment by AlexM392** [comment]
Got it. I'll implement controlled version.
Could you please tell me, does the 'apiRef.current.setItemExpansion' method is allowed using the controlled version of the tree items expansion?

**Comment by LukasTy** [comment]
Yes, you can mix and match `apiRef` with an explicit `expandedItems` setting.
[Here is an example](https://stackblitz.com/edit/zpnue4iw?file=src%2FDemo.tsx) of doing it.
Is there something else you need help with?

**Comment by AlexM392** [comment]
Thank you so much! You helped me a lot!
This is exactly what I wanted to know.

**Comment by LukasTy** [comment]
I'm closing the issue, since the issue seems to be resolved.
If you think something is still unclear, feel free to reopen this issue or create a new one.

**Comment by AlexM392** [comment]
Hello @LukasTy.
Unfortunately, I do not have permission to reopen the issue 
<img width="483" height="92" alt="Image" src="https://github.com/user-attachments/assets/1ee2d253-0897-404c-8ee6-4eb9a89e86c6" />
But it does not matter. The deal is that, I implemented the solution with mixing and matching apiRef with an explicit expandedItems setting. By doing this, the tree loses the smoothness of the node opening.
Could you please check the [DEMO](https://stackblitz.com/run?file=Demo.tsx) and confirm that the problem is in old versions of dependencies? Or it's something else?...
Please note that clicking on an element only opens it, but does not close it.

I've just checked the demo and can't understand why I can't share it properly. On my side I have the preview:
<img width="1654" height="534" alt="Image" src="https://github.com/user-attachments/assets/228a97a6-24d3-4b8e-9dc1-c34d038da03c" />

But if I click the link, I got:
<img width="1508" height="384" alt="Image" src="https://github.com/user-attachments/assets/05f5350c-a200-4c0d-b027-75e1551183b8" />

**Comment by LukasTy** [comment]
> Unfortunately, I do not have permission to reopen the issue

Thanks for pointing this out. 🙏 
@michelengelen, do you know if something changed in permission settings?
AFAIK, issue authors were able to reopen issues at least for some specific time after closing them... 🤷‍♂️ 

___

> Could you please check the [DEMO](https://stackblitz.com/run?file=Demo.tsx) and confirm that the problem is in old versions of dependencies?

@AlexM392 Have you made sure the project is public? 🤔 
The project has to be public, and then click "Copy URL".

<img width="1589" height="534" alt="Image" src="https://github.com/user-attachments/assets/f0285654-6c6d-42f4-a3a1-3701a5e01048" />

Different `@mui/x-tree-view` and `@mui/material` package majors should not be related to it.
A particular behavior combination might not behave as expected...

**Comment by AlexM392** [comment]
Yes, it's public:

<img width="1082" height="486" alt="Image" src="https://github.com/user-attachments/assets/08648a77-6ae5-4556-91a0-34529c919008" />

And here is the same link :
https://stackblitz.com/edit/71fpkqzm-gjt6jfsw?file=index.html

Unfortunately, with the same result ((

I'm trying to make the demo via Sandbox

UPD: I tried to base the demo on the customisation demo from the official site, but unfortunately, Sandbox has the problem with the preview too:

<img width="1587" height="705" alt="Image" src="https://github.com/user-attachments/assets/e418611a-c7c8-4ecf-82ea-65fde3e112d4" />
<img width="1130" height="881" alt="Image" src="https://github.com/user-attachments/assets/90c36e9f-437e-4c66-a563-31744938c118" />

UPD: I've implemented your solution to the newest version, using the demo on the official site - everything works properly.

**Comment by LukasTy** [comment]
> UPD: I've implemented your solution to the newest version, using the demo on the official site - everything works properly.

Thanks for clarifying. 🙏 
v7 might not be as refined as the latest v8 version as Tree View was in very active development on v7.
Does this discovery unblock you or is there still a problem you need help with? 🤔

**Comment by AlexM392** [comment]
I need to update my Tree View to version 8 whatever it takes - this is the only solution.
Thank you for your patience and help!

**Comment by michelengelen** [comment]
For reference @LukasTy and @AlexM392: You can only reopen an issue under 2 conditions:
1. you are a collaborator on the repo/org
2. you are the issue author and closed the issue yourself
