### ISSUE TITLE
[question] Band between two lines

### ISSUE THREAD

**Issue by oscar-b** [mui/mui-x#19726]
### Order ID or Support key 💳

100737

### Search keywords

band

### Latest version

- [x] I have tested the latest version

### Affected products

Charts

### The problem in depth

I'm trying to create a "band" between two lines, showing an area indicating min/max values, inspired by https://mui.com/x/react-charts/line-demo/#line-with-forecast

I can't get it to line up properly with the line curve though, any ideas on how to fix this?

<img width="848" height="387" alt="Image" src="https://github.com/user-attachments/assets/b72ac521-1e55-4ba9-9a39-c06bf13b66a2" />

https://stackblitz.com/edit/cv6cxcq8?file=src%2FDemo.tsx

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by bernardobelchior** [comment]
By default, there's a `categoryGapRatio` of 0.2. If you set it to 0 in the `xAxis`, it should fix the issue:

<img width="1344" height="911" alt="Image" src="https://github.com/user-attachments/assets/bf330b4a-1ffd-439e-a669-ab43f3b5c85b" />

[StackBlitz](https://stackblitz.com/edit/cv6cxcq8-7hh65cd5?file=src%2FDemo.tsx)

**Comment by oscar-b** [comment]
> By default, there's a categoryGapRatio of 0.2. If you set it to 0 in the xAxis, it should fix the issue:

Oh wow that totally seems to do the trick! Thank you! <3

**Comment by oscar-b** [comment]
> By default, there's a `categoryGapRatio` of 0.2. If you set it to 0 in the `xAxis`, it should fix the issue:

Oh hmm except the little problem that this will also affect the actual bars that's supposed to also be rendered here, with the actual values (the band being in the background). Found `barGapRatio` but it didn't seem to affect the bars.

And having a separate x-axis is problematic since I want the "nice" domain calculations from the real data, and I still don't think there's a way to transfer min/max to another axis?

**Comment by bernardobelchior** [comment]
> And having a separate x-axis is problematic since I want the "nice" domain calculations from the real data, and I still don't think there's a way to transfer min/max to another axis?

I can't think of a way to make that happen automatically, but you can make it work manually. 

If you set the `domainLimit` to `'strict'` and calculate the nice domain (using [`d3-array`'s `nice()`](https://d3js.org/d3-array/ticks#nice)), then setting both axes' min and max values to the nice domain should ensure your axes always align on the domain. 

If you provide a reproduction of the issue I can try to be of more help

**Comment by oscar-b** [comment]
> > And having a separate x-axis is problematic since I want the "nice" domain calculations from the real data, and I still don't think there's a way to transfer min/max to another axis?
> 
> I can't think of a way to make that happen automatically, but you can make it work manually.
> 
> If you set the `domainLimit` to `'strict'` and calculate the nice domain (using [`d3-array`'s `nice()`](https://d3js.org/d3-array/ticks#nice)), then setting both axes' min and max values to the nice domain should ensure your axes always align on the domain.
> 
> If you provide a reproduction of the issue I can try to be of more help

I updated the repro now: https://stackblitz.com/edit/cv6cxcq8?file=src/Demo.tsx,src/Band.tsx

So I want regular bars like this, but the background band without the shifted grey area:

<img width="677" height="387" alt="Image" src="https://github.com/user-attachments/assets/cc54de05-cfce-4564-a74f-4d9523d24e4d" />

**Comment by bernardobelchior** [comment]
Something [like this](https://stackblitz.com/edit/cv6cxcq8-dbwubstn?file=src%2FDemo.tsx)?

<img width="537" height="396" alt="Image" src="https://github.com/user-attachments/assets/fbb0e685-0aaf-4abf-9c31-809bbafe3c0e" />

The idea is to create a second x-axis with `categoryGapRatio: 0`. We set `position: 'none'` so it's hidden, otherwise we'd have two axes. Then we update the two last series and the `Band` component to use this new x-axis called `second`. The blue bars remain using the original x axis.

**Comment by oscar-b** [comment]
> The idea is to create a second x-axis with `categoryGapRatio: 0`. We set `position: 'none'` so it's hidden, otherwise we'd have two axes. Then we update the two last series and the `Band` component to use this new x-axis called `second`. The blue bars remain using the original x axis.

Oh very nice, thank you very much! This is another x-axis and not another y-axis, so there's no issue with them having different domain scaling! I think this fully resolves my issue, I'll have a stab at implementing it properly today 🎉

**Comment by prakhargupta1** [comment]
Hey @oscar-b ,

Great to see that your issue has been resolved. I am curious to learn more about the use case where you needed such a band pattern in the background of the bar chart. If you are open to share more about it, I would like to [invite](https://calendar.app.google/ttsGf7zwcAGDQibN8) you to a 30-min user interview. We'll also discuss your experience with charts so far and if you have any feature requests. Thanks :)

**Comment by oscar-b** [comment]
@prakhargupta1 Feel free to reach out to me by email, it should be visible in my profile!
