### ISSUE TITLE
DataGridPro useResizeContainer - The parent of the grid has an empty width

### ISSUE THREAD

**Issue by igorSurz** [mui/mui-x#4911]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I am begging you to help me because I have been looking for an answer for 3 days, and I can't fix this.

Problem: MUI: useResizeContainer - The parent of the grid has an empty width. You need to make sure the container has an intrinsic width. The grid displays with a width of 0px.

### Expected behavior 🤔

https://stackoverflow.com/questions/72255933/mui-datagridpro-useresizecontainer-the-parent-of-the-grid-has-an-empty-width

You can see the full description with screenshots here on StackOverflow, I need help from the MUI team, why does Data Grid Pro cant understand that it is not 0px width and its container is not 0 px width as well

Expected behavior: not to throw me that error 😇

### Steps to reproduce 🕹

pass MUI Data Grid Pro to Mui Side Drawer 

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
I use Chrome 

System:
    OS: macOS 12.3.1
  Binaries:
    Node: 16.13.2 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.1.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 101.0.4951.64
    Edge: Not Found
    Firefox: Not Found
    Safari: 15.4
```
</details>

**Comment by flaviendelangle** [comment]
Hi,
Thanks for your contribution.

Could you provide a working reproduction, this [Codesandbox template](https://codesandbox.io/s/datagrid-v5-quick-start-54iz1) might be a good starting point.

**Comment by flaviendelangle** [comment]
Here is a fixed link: https://codesandbox.io/s/data-grid-community-forked-vftqr5

**Comment by igorSurz** [comment]
> Here is a fixed link: https://codesandbox.io/s/data-grid-community-forked-vftqr5

I will try  to reproduce it in another way, but for now, I put my code into it and I cant see this error 
https://codesandbox.io/s/data-grid-community-forked-vb30w3?file=/src/Drawer.js

or if there is an opportunity to get a short demonstration in zoom may be?
I think It will help us much faster then I will try not to paste 1000 rows of code to sandBo)))))

**Comment by igorSurz** [comment]
> Without a clear reproduction case that I can play with, it is very hard to debug something.

https://codesandbox.io/s/data-grid-community-forked-08nfbq?file=/src/Drawer.js
Can you please now help me? added all of my code

**Comment by igorSurz** [comment]
> I don't see any problem on your exemple (https://codesandbox.io/s/data-grid-community-forked-lcnkde I just fixed some deps to have it render correctly)

I don't understand, you are right, no errors in the sandbox, just with the license key, I have one so there is no such error on my machine, but its the same code, copy\paste
and I have still the same error with sizes  on my local machine
maybe screenshot will help?
![image](https://user-images.githubusercontent.com/100679570/169239297-0ebd2f62-7bc8-4d8a-ab75-41ffd2a6e476.png)

**Comment by igorSurz** [comment]
fixed by myself

**Comment by Jova266** [comment]
How did you fix it?

**Comment by 1antares1** [comment]
In my case, the DataGridPro was inside a tab that was not visible and I only set the parent (immediate element above `width: 100%`) and it no longer generated an error.

**Comment by DGeretz** [comment]
adding in the autoHieght prop took care of this error for me
`<Box
          sx={{
            width: '100%',
          }}
        >
          <DataGrid
            rows={orders.orders}
            columns={PENDING_ORDERS}
            autoHeight
          />
        </Box>`

**Comment by GBS-Huezo** [comment]
I've tried adding the height and width to the immediate parent element of the DataGridPremium and I'm still getting the error. Though I think it might be because I'm conditionally hiding the div depending on the current view we're in. Here is the little snippet
```
<div hidden={currentView === "grid" ? "" : "hidden"} style={{ width: "100%", height: 600 }}>
     <DataGridPremium></DataGridPremium>
</div>
```

I'm working on putting together a code sandbox of a closely similar setup to the code I'm working with. In the meantime, I'm wondering if anyone would know what the issue would be.

**Comment by AndreaPrillo** [comment]
Hi @GBS-Huezo , I have the same problem. Did you find a solution for it?

**Comment by nycgavin** [comment]
same annoying error message

**Comment by SultanaJon** [comment]
Similarly to @GBS-Huezo, I was also conditionally setting the `visibility` attribute to the parent element of the `DataGrid`. To fix the issue, instead of conditionally settings the parent `visibility` or `hidden` attribute, simply return null as the component so nothing is rendered in view.

``` typescript
export default function MyComponent() {
  return (
    someCondition ? <DataGrid ...props /> : null
  )
}
```

**Comment by rkuang9** [comment]
Problem with rendering something else like null instead of the DataGrid, it loses its state (current page, rows per page, etc).

**Comment by Bonfims** [comment]
i want show a table view with a loading icon or the message with no rows, why i need to make it conditionally rendered?

**Comment by brilliantinsane** [comment]
What to do now when autoHeight is deprecated and we have to use flex container with flexDirection: column? When I do that, it is failing. I get this same annoying error.

It is also happening only in chrome or chromium based browsers. In safari or mozila it is working just fine. So, someone please tell me what is going on? IDK if I can provide a minimum reproducible but isn't it weird that my code is working fine in safari/mozila but failing in chrome/brave?

![Image](https://github.com/user-attachments/assets/ec879d00-eb30-428b-9b2e-487aa3b24a10)

**Comment by emagombe** [comment]
> What to do now when autoHeight is deprecated and we have to use flex container with flexDirection: column? When I do that, it is failing. I get this same annoying error.
> 
> It is also happening only in chrome or chromium based browsers. In safari or mozila it is working just fine. So, someone please tell me what is going on? IDK if I can provide a minimum reproducible but isn't it weird that my code is working fine in safari/mozila but failing in chrome/brave?
> 
> ![Image](https://github.com/user-attachments/assets/ec879d00-eb30-428b-9b2e-487aa3b24a10)

Same error after upgrading to MUI 7

![Image](https://github.com/user-attachments/assets/df71e6e1-50d6-45b4-ac68-f8cb00cb5b54)

![Image](https://github.com/user-attachments/assets/15ad8fc1-eed3-4b46-8931-4ab8bdd407ba)

**Comment by emagombe** [comment]
> [@emagombe](https://github.com/emagombe) Don't wrap the `DataGrid` in a `Box` component—replace Box with a div. It worked for me.

Didn't work. I have the DataGrid inside a Dialog. It works used to work perfectly when using MUI6. But after moving to MUI 7 the problem begins.

`<Box>
			<Dialog
				open={open}
				onClose={on_close}
				fullWidth
				maxWidth="lg"
				TransitionComponent={Transition}
				PaperProps={{}}
			>
				{loading ? <LinearProgress color="secondary" /> : ""}
				<DialogTitle>
					<FormattedMessage defaultMessage="Client" />
				</DialogTitle>
				<DialogContent>
					<div
						sx={{
							mt: 2,
						}}
					>
						<DataGrid
							autoHeight
							autosizeOnMount
							rows={data_list}
							filterMode="server"
							loading={loading}
							columns={columns}
							disableMultipleRowSelection
							disableSelectionOnClick
							disableRowSelectionOnClick
							sortingMode="server"
							paginationMode="server"
							rowCount={total_rows}
							disableColumnMenu
							disableColumnResize
							getRowHeight={getRowHeight}
							paginationModel={{
								page: current_page,
								pageSize: per_page,
							}}
							sortModel={[
								{
									field: order_column,
									sort: order == 0 ? "desc" : "asc",
								},
							]}
							onRowClick={onRowClick}
							pageSizeOptions={[10, 50, 100, 500, 1000]}
							onPaginationMetaChange={onPaginationMetaChange}
							onPaginationModelChange={onPaginationModelChange}
							onSortModelChange={onSortModelChange}
							sx={{
								"&.MuiDataGrid-root .MuiDataGrid-cell:focus-within": {
									outline: "none !important",
								},
								"& .MuiDataGrid-row:hover": {
									backgroundColor: theme.palette.secondary.dark,
									cursor: "pointer",
								},
							}}
							slotProps={{
								loadingOverlay: {
									variant: "skeleton",
									noRowsVariant: "skeleton",
								},
							}}
							localeText={{
								MuiTablePagination: {
									labelRowsPerPage: intl.formatMessage({ defaultMessage: "Rows per page" }),
									labelDisplayedRows: ({ from, to, count }) => {
										return `${from} - ${to} ${intl.formatMessage({ defaultMessage: "of" })} ${count === -1 ? `${intl.formatMessage({ defaultMessage: "more than" })} ${to}` : count}`;
									},
								},
							}}
						/>
					</div>
				</DialogContent>
				<DialogActions>
					<Button
						size="small"
						onClick={on_close}
						disabled={loading}
					>
						<FormattedMessage defaultMessage="Close" />
					</Button>
				</DialogActions>
			</Dialog>
		</Box>`

Also, the same table is well rendered when it is outside of a Dialog. But the system we built is Dialog based which makes it impossible to move from MUI 6 to MUI 7.

**Comment by emagombe** [comment]
Fixed by adding **open** parameter to the fetch data useEffect. So that way, when the modal is opened it calculates the width correctly. But the error message is still being shown on console.

```javascript
useEffect(() => {
	clearTimeout(timeout);
	timeout = setTimeout(() => {
		fetch_data();
	}, 100);
}, [open, current_page, per_page, order, order_column, search, date_start, date_end]);
````

At least for now, we can keep moving!

**Comment by fenixburnaby** [comment]
I had to add an state flag to display the data grid after the component was completely rendered, similar to what @emagombe did. Here is my code:

```javascript
  React.useEffect(() => {
    setTimeout(() => {setDisplayDatagrid(true);});
  }, []);
```

This waits until the rest of the layout is complete, and then I can render the Grid taking the space it should

```javascript
{displayDataGrid && (
        <MUIBox sx={{ width: '100%', mt: 5, mb: 5 }}>
          <MUIDataGrid
            rows={tempRows}
            columns={tempColumns}
            initialState={{
              pagination: {
                paginationModel: {
                  pageSize: 5,
                },
              },
            }}
            pageSizeOptions={[5, 10, 20]}
            disableRowSelectionOnClick
          />
        </MUIBox>
      )}
```
