### ISSUE TITLE
[fields] The expanded format is not correct when using `luxon`

### ISSUE THREAD

**Issue by rodrigofariow** [mui/mui-x#7615]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

I noticed some time formats are not consistent between `NextTimePicker` and `NextDateTimePicker`.

For instance, on `NextTimePicker` the behaviour for locale `pt-PT` is fine:
https://codesandbox.io/s/boring-albattani-bppmff?file=/demo.tsx

I'm able to write an hour within the 24h system (which is correct for pt-PT):
![image](https://user-images.githubusercontent.com/22502084/213237033-ab9a1a30-267d-4d72-86a9-24de51641f6d.png)

For `NextDateTimePicker` the behaviour for locale `pt-PT` is faulty:
https://codesandbox.io/s/vibrant-rumple-23d0uh?file=/demo.tsx

I'm not able to write an hour past 12. For instance, if I want to write 13 it just shows 1:
![image](https://user-images.githubusercontent.com/22502084/213238742-d722ba23-f5ed-427c-b6d5-83e1906ad1ec.png)

Not sure if this is a problem with `luxon` or `NextDateTimePicker` but I was hoping you could clarify.

Thanks!

### Your environment 🌎

System:
    OS: macOS 13.1
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Chrome: 109.0.5414.87
    Edge: Not Found
    Firefox: Not Found
    Safari: 16.2
  npmPackages:
    @emotion/react: 11.10.4 => 11.10.4 
    @emotion/styled: 11.10.4 => 11.10.4 
    @mui/icons-material: 5.11.0 => 5.11.0 
    @mui/lab: 5.0.0-alpha.113 => 5.0.0-alpha.113 
    @mui/material: 5.11.1 => 5.11.1 
    @mui/system: 5.11.1 => 5.11.1 
    @mui/x-data-grid: 6.0.0-alpha.14 => 6.0.0-alpha.14 
    @mui/x-data-grid-generator: 6.0.0-alpha.14 => 6.0.0-alpha.14 
    @mui/x-data-grid-premium: 6.0.0-alpha.14 => 6.0.0-alpha.14 
    @mui/x-data-grid-pro: 6.0.0-alpha.14 => 6.0.0-alpha.14 
    @mui/x-date-pickers: 6.0.0-alpha.15 => 6.0.0-alpha.15 
    @mui/x-date-pickers-pro: 6.0.0-alpha.15 => 6.0.0-alpha.15 
    @types/react: 18.0.25 => 18.0.25 
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    styled-components: 5.3.5 => 5.3.5 
    typescript: 4.9.4 => 4.9.4 

### Order ID 💳 (optional)

54728

**Comment by flaviendelangle** [comment]
Hi,
Thanks for your feedback !

The format used by the date-time pickers for Luxon is `D T` which translates into `d/M/yyyy h:m` (`h` being a 12 hour time).

I think the `expandFormat` of Luxon is not returning the correct format.
[Live example](https://codesandbox.io/s/date-and-time-pickers-forked-rmhkgi?file=/src/App.tsx)

We should always have `someDate.setLocale(locale).toFormat(format) === someDate.toFormat(DateTime.expandFormat(format, { locale }))`

**Comment by alexfauquette** [comment]
This reminds me the usual issue we get with the mask when using luxon. The digits do not use trailing zeros which was breaking the mask.

For now, we respect trailing zeros according to the library format. So if in the hour section you press
- <kbd>0</kbd><kbd>3</kbd> it displays `3` (no trailing zero)
- <kbd>1</kbd><kbd>2</kbd> it displays `12`
- <kbd>1</kbd><kbd>3</kbd> it displays `1` and goes to the next section

We have two problems here:

First for input not having the trailing zeros is disturbing. Maybe they should be set by default (even if the format says not to) and add a prop to disable them as follow:

<table>
<tr>
	<td>format
	<td>`disableTrailingZeros`
	<td>result
<tr>
	<td>`dd`
	<td>`true`
	<td>05
<tr>
	<td>`dd`
	<td>`false`
	<td>05
<tr>
	<td>`d`
	<td>`true`
	<td>5
<tr>
	<td>`d`
	<td>`false`
	<td>05
</table>

The second issue is the behavior of pressing <kbd>1</kbd><kbd>3</kbd> which in my opinion should display 3 before going to the next section

**Comment by flaviendelangle** [comment]
> Bug when 2 digits is over the max

That one is indeed on our side.
When using 12 hours format, we should have an upper boundary of `12` on the hours, not `24`

**Comment by flaviendelangle** [comment]
> First for input not having the trailing zeros is disturbing. Maybe they should be set by default (even if the format says not to) and add a prop to disable them as follow:

I'm not a fan of playing that much with the format.

**Comment by flaviendelangle** [comment]
For the `expandFormat` which is not working correctly in Luxon.
I think they just don't know what the actual token is... They hardcode one token per date section https://github.com/moment/luxon/blob/e78105211d8161a218b2e7518adc333c3b2e312b/src/impl/tokenParser.js#L197

Which is clearly not sufficient for our use case, but might be for what they did with it before I asked for `expandFormat`.

**Comment by flaviendelangle** [comment]
I did a little digging and it won't be an easy one to fix...

Internally, Luxon never expand the "macro token" (`D`, `T`).

When parsing a macro token, it directly creates the object describing the format (is it numerical ? it is 24h etc...).
So the `expandFormat` method tries to work around that and just return one token for the hour, one for the minute etc... with some logic (see the `partTypeStyleToTokenVal` object).

I fear that we won't have a clean solution without heavy work on Luxon :cry:

**Comment by alexfauquette** [comment]
> And each local decides which format to use

I agree but the format could depend on the context.

For example, if you ask me to write 9:15 as you can see I tend to do not add the zero before 9. But in a computer input, having the zero before would not be a problem since I'm used to digital clocks.

The idea would be to have a prop to say "Add trailing zero" (naming depending if the default is `true` or `false`) whic would be easier than overriding the format. Plus it allows keeping localisation for other topics (for example french=`dd/mm/yyyy` or german=`dd-mm-yyyy` or usa:`mm/dd/yyyy`)

**Comment by rodrigofariow** [comment]
Thanks for providing an alternative @flaviendelangle @alexfauquette .

This makes me worried, tough. 
Does this mean luxon won't be fully suported with the new pickers?
Is it the only known adapter to not work well for this use case out of the box?

**Comment by flaviendelangle** [comment]
From what I understand, it means that Luxon does not have a way to reliably expand macro tokens.
We can work with the Luxon maintainer to make this expansion as reliable as possible (having the 24 hours format instead of the 12 hours one should be doable I hope for example).
And we can make sure to never use the non-expanded format to parse a date (since the expanded format does not always represent the correctly the non-expanded format).

My hope is that we can have a behavior correct for the commonly used formats.

___

As far as I know, the other date libraries don't rely on `Intl`, they do the parsing themselves.
So they have a very different approach which should not be problematic for our components.
I did most of my development with `dayjs` and `date-fns` and never encountered a similar issue.

**Comment by flaviendelangle** [comment]
https://user-images.githubusercontent.com/3309670/213440654-21f12ce8-fbc7-4e1d-a619-ac238bfd1022.mp4

I think I have something working on Luxon
I'll open a PR on their repo to discuss the changes

**Comment by ddolcimascolo** [comment]
Hi @flaviendelangle 

Can you post an update on this issue? Luxon has made some progress I think.

Thanks,
David

**Comment by ddolcimascolo** [comment]
Excellent, I see that the fix got merged 👍

**Comment by rodrigofariow** [comment]
Hi @flaviendelangle 

I've forked luxon from their master branch and it looks like the hour issue is solved:
<img width="296" alt="image" src="https://user-images.githubusercontent.com/22502084/230122060-750422db-32eb-45aa-88e5-424030f17b68.png">

I'm afraid the leading zeros will be a problem, regardless.
Can we expect mui to provide a workaround for this soon or is this going to be a problem for a while?

Unfortunately, this issue has been a blocker for my team for a few months (we are still stuck with 6.0.0-alpha.15).
It would be awesome if you guys could provide a workaround for the leading zeros so that all devs blocked by this issue can safely adopt the new pickers without having to worry about these other edge cases.
It would be very much appreciated. 🙏 

Cheers!

**Comment by ddolcimascolo** [comment]
+1 of course, this is quite a long delay for getting a proper fix...

**Comment by flaviendelangle** [comment]
For the leading zeros, I'm working on it in #8527

We can't rush a fix related to format rendering and parsing, it can easily break a lot of applications.

**Comment by ddolcimascolo** [comment]
Hi all and @flaviendelangle

Thx for merging the leading zeroes fix in 6.3.0, it's much better now. Any news on this as it seems it's the only usability issue remaining with the `<Date Time Picker />` component, at least for my use case in French locale.

Thx,
David

**Comment by flaviendelangle** [comment]
:pray: Thanks for the feedback !

Closing this one, if anyone has a format not working well with Luxon, feel free to comment and I will re-open if needed :+1:

**Comment by genepaul** [comment]
I just wanted to understand if there is work in progress to support the macro tokens, as your documentation links here, but as this issue is closed it leads one to believe that it should be fixed. When I try to use `DD` as a format in Date fields, I get the following error:

```
Error: MUI: The token "de" is not supported by the Date and Time Pickers.
```

Do you have a tracking issue?

**Comment by alexfauquette** [comment]
@genepaul I can not reproduce your issue. Since this one is closed, please open a new one with a minimal reproduction example such that we can identify the bug and track progress on it

https://codesandbox.io/s/divine-hill-rrkdqk?file=/Demo.tsx

**Comment by genepaul** [comment]
Issue created: #10177
