### ISSUE TITLE
[pickers] `renderInput` not working on v6 (should have a warning)

### ISSUE THREAD

**Issue by ChineseOuchie** [mui/mui-x#8176]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:
https://codesandbox.io/s/serene-morse-k5zkkw?file=/demo.js

### Current behavior 😯

I have 3 Datepicker with 3 different textfield variant, but all of them are showing the "outlined" styling

![image](https://user-images.githubusercontent.com/10912994/223712997-0c2eac56-6bdb-4096-a4d6-3e6edc184aad.png)

### Expected behavior 🤔

To see 3 different design

**Comment by flaviendelangle** [comment]
Hi,

On the codemod you are using the `latest` version, which is now 6.0.0
This new version is no longer using the `renderInput` prop
You can have a look at the [migration guide](https://next.mui.com/x/migration/migration-pickers-v5/#input-renderer-required-in-v5) if you are willing to upgrade (we have some cool feature in the major release and other on the way) or downgrade to the last v5 release if a migration is to costly for now.

**Comment by ChineseOuchie** [comment]
That explains a lot, thanks👍.

**Comment by geekysaurabh001** [comment]
Hi, was searching the same but my use case is different:

```js
renderInput={(params: any) => {
  params.inputProps.type = "button";
  params.inputProps.onClick = () => setIsDatePickerOpen(true);
  return <TextField {...params} />;
}}
```

This was inside the DatePicker component. But now, I don't see in the migration guide how to make this work?

**Comment by geekysaurabh001** [comment]
Hi @LukasTy I already tried that but unlike before, it gives the error of "Failed to execute 'setSelectionRange' on 'HTMLInputElement': The input element's type ('button') does not support selection". This wasn't the case before.

**Comment by LukasTy** [comment]
Ah, yes, good point.
In v6 the `input` is much more elaborate to simply be changed into a button in this way.
What is your exact use case?
Maybe [this example](https://mui.com/x/react-date-pickers/custom-field/#using-a-button) using a button would steer you in the right direction? 🤔

**Comment by LukasTy** [comment]
> The update broke this behaviour.

It doesn't seem that the update broke the accepted behavior in the StackOverflow answer. 🤔 
[Here is](https://codesandbox.io/s/67053310-material-ui-open-datepicker-when-clicking-anywhere-in-the-textfield-forked-pzgtlj?file=/demo.js) the same example adjusted to v6 API.
In your case, the root cause of the problem is the `type="button"`, which indeed breaks the `fields` behavior.

If you do not intend to benefit from all the features that [v6 field components](https://mui.com/x/react-date-pickers/fields/) bring, you can consider simplifying your use case and overriding the `field` slot with a more simple implementation to gain some performance improvements. 🤔

**Comment by geekysaurabh001** [comment]
I have implemented this now. This seems to be working just fine. Now I just have to remove the calendar icon here and the use case satisfies.

```ts
<DatePicker
              open={isDatePickerOpen}
              onOpen={() => setIsDatePickerOpen(true)}
              onClose={() => setIsDatePickerOpen(false)}
              value={allowedDate}
              onChange={setAllowedDate}
              disablePast
              slotProps={{
                toolbar: {
                  hidden: true,
                },
                textField: {
                  InputProps: {
                    className: "dateField",
                  },
                  role: "button",
                  onClick: () => setIsDatePickerOpen(true),
                  onKeyDown: (e) => {
                    if (e.code === "Enter" || e.key === "Enter") {
                      setIsDatePickerOpen(true);
                    }
                  },
                },
              }}
              shouldDisableDate={isWeekendAfter5}
              maxDate={maxDate}
              format="do MMMM yyyy"
            />
```

**Comment by LukasTy** [comment]
> This new approach is so limited it's just frustrating at this point.

Could you clarify what you find limiting in this approach?
Technically, it allows all the same possibilities, just with a bit different approach and option to have better performance with less remounting. 🤔

**Comment by geekysaurabh001** [comment]
I am trying to use PickersDay to have custom styling around the dates:

1. Have logic to disable certain dates.
2. Style disabled dates differently.
3. Select Multiple dates with custom background styles.

Previously, the renderDay prop allowed custom manipulation without any confusion with custom logic. Now, it's not.

**Comment by LukasTy** [comment]
> Previously, the renderDay prop allowed custom manipulation without any confusion with custom logic. Now, it's not.

Have you checked the example of a [custom `day` slot](https://mui.com/x/react-date-pickers/date-calendar/#week-picker) usage? 🤔 

Sorry, but I still fail to understand, what you find unable to do on v6 as [compared to v5](https://v5.mui.com/x/react-date-pickers/date-picker/#customized-day-rendering)? 🤷 
The only clear difference is that in order to pass custom props to the custom `Day` component, you no longer need to define this component inside of your Picker component because the custom props can be passed via the `slotProps.day`.

**Comment by geekysaurabh001** [comment]
Yes saw that. Not helpful. Never mind. I find v5 better for date-picker as it allowed better minute controls.

**Comment by LukasTy** [comment]
That is understandable.
The change to `slots` and `slotProps` is in an effort to unify API between all the components and MUI libraries.
As for simplicity, naturally, every new version will have more features and it can already feel less straightforward to use because of that.
We understand that getting used to the `slots` mental model might take time. There is also [some documentation content](https://mui.com/x/react-date-pickers/base-concepts/#overriding-slots-and-slot-props) available to help get you started. 😉

**Comment by dmaindolaivp** [comment]
@LukasTy I had a wrapper over the mui datepicker v5 earlier and it used to take renderInput in props. Earlier only textfield (another wrapper over mui textfield) was expected but now i need to support anything that is sent. Basically it can be our wrapper components or a simple button/input even a div. How can i go about this?

**Comment by LukasTy** [comment]
> How can i go about this?

Maybe [this example](https://mui.com/x/react-date-pickers/custom-field/#using-a-button) of using a button as the trigger for the picker would also help you. 🤔 
If it doesn't help, please clarify what problem are you facing. 🙏 
The biggest change in v6 in such a case is that we introduced the `Field` concept, which expects the underlying component to be an input that it can interact with.
If you want a completely different experience than input, you'll need to override the `field` slot.

**Comment by dmaindolaivp** [comment]
@LukasTy Here is the code sandbox: https://codesandbox.io/s/bold-surf-ky236h?file=/src/App.js

My wrapper component earlier used to take just a textfield (wrapper of mui textfield only) in renderInput prop and pass it as it is to the renderInput that the mui DatePicker/DateTimePicker's renderInput prop used to take.

Now i have to maintain backwards compatibility and also allow users to send pretty much anything. A div, textfield, button anything. I have to open the picker relative to the sent component obviously. 

I am struggling to give ref to the received component and also getting some undefined properties error when i do use some other inputs or buttons. Sometimes this **focus** error or sometimes **contentType** undefined error.

**Comment by LukasTy** [comment]
@dmaindolaivp [Here is](https://codesandbox.io/s/suspicious-snowflake-45wv6t?file=/src/CustomDatePicker.js) a working fork of your codesandbox.
There were two problems:
1. You were overriding the `inputRef` with an internal ref that was not being used anywhere
2. You were not passing the `ref` to `button` and `input` elements
