### ISSUE TITLE
[pickers] Date Range Picker fields are broken on Safari

### ISSUE THREAD

**Issue by davevanhoorn** [mui/mui-x#9003]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

Steps:
1. Visit the [MUI X Date Range Picker](https://mui.com/x/react-date-pickers/date-range-picker/) page in either Firefox (113.0.1) or Safari (16.4) or MS Edge (113.0.1774.42)
2. Go to the [Basic Usage](https://mui.com/x/react-date-pickers/date-range-picker/) example
3. Enter a date (e.g. `05-13-1989`) in the `Check-in` picker without using the modal
4. Use `tab` on your keyboard to navigate to the `Check-out` picker
5. Notice that the input field focuses on the `year`, and not on the `month`

**Screen recording for Firefox (same result in MS Edge):**
https://github.com/mui/mui-x/assets/1295837/fc60f38e-1787-41f8-982b-88c38576bd3f

**Screen recording for Safari:**
https://github.com/mui/mui-x/assets/1295837/c836c45c-1090-42f8-951a-c135f6407977

### Current behavior 😯

When using tabs to navigate to the second input field in a Date Range Picker, the input is focused on the `year`.

### Expected behavior 🤔

When using tabs to navigate to the second input field in a Date Range Picker, the input should be focused on the first element of the input field (which in my case is the `month`)

### Context 🔦

As a paying customer I'd like to work with a Date Range Picker that behaves the same in different (modern) browsers. **Safari is currently (version `6.4.0`) unusable.** (link to [screen recording](https://github.com/mui/mui-x/assets/1295837/c836c45c-1090-42f8-951a-c135f6407977)).

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 13.3.1
  Binaries:
    Node: 20.1.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.6.4 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 113.0.5672.92
    Edge: 113.0.1774.42
    Firefox: 113.0.1
    Safari: 16.4
  npmPackages:
    @emotion/react: ^11.10.6 => 11.10.6 
    @emotion/styled: ^11.10.6 => 11.10.6 
    @mui/material: ^5.12.1 => 5.12.1 
    @mui/x-date-pickers: 6.4.0 => 6.4.0 
    @mui/x-date-pickers-pro: 6.4.0 => 6.4.0 
    @mui/x-license-pro: 6.0.4 => 6.0.4 
    @types/react: ^18.0.37 => 18.0.37 
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    typescript: ^4.9.5 => 4.9.5 
```
</details>

### Order ID or Support key 💳 (optional)

66464

**Comment by alexfauquette** [comment]
The Fierfox issue should be solved by https://github.com/mui/mui-x/pull/9005

You can test the docs preview [here](https://master--material-ui-x.netlify.app/x/react-date-pickers/date-range-picker/)

**Comment by davevanhoorn** [comment]
Thanks for fixing the Firefox issue so quick @alexfauquette.

Do you have any update on the Safari bug?

**Comment by karapalumbo** [comment]
Hello, this looks like it’s still an issue on Chrome using the datepicker. I believe it has something to do with the onFocus prop. Can you advise if this has been fixed in all browsers?

**Comment by LukasTy** [comment]
Could you confirm what is the actual issue that you are still experiencing?
We have just recently merged a related fix targeting DateTimePicker https://github.com/mui/mui-x/pull/9342, you can [check the docs](https://deploy-preview-9342--material-ui-x.netlify.app/x/react-date-pickers/date-time-picker/) with that particular fix and identify if the issue you are having is still present.
The mentioned fix will be released at the end of the week.
